export const INVENTORY_CATEGORIES = [
  {
    id: "unit-of-measure",
    permissions: {
      view: "view-units",
      create: "create-units",
      edit: "edit-units",
      delete: "delete-units",
    },
    searchKey: "name",
    endpoints: {
      list: "/admin/units",
      createData: "/admin/units/create",
      editData: (id: number) => ({
        endpoint: `/admin/units/${id}/edit`,
        itemKey: "unit",
      }),
      create: "/admin/units",
      update: "/admin/units",
      delete: "/admin/units",
    },
    formFields: [
      {
        key: "name",
        name: "unit_name",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "short_code",
        name: "short_code",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "conversion_factor",
        name: "conversion_factor",
        type: "number",
        value: 1,
        required: true,
        child: {
          key: "base_unit_id",
          name: "base_unit_id",
          type: "select",
          value: "",
          required: false,
          options: [],
          optionsKey: "units",
        },
      },
      {
        key: "status",
        name: "status",
        type: "status",
        value: "active",
        options: [],
        optionsKey: "status",
        required: true,
      },
    ],
    tableKeys: [
      "name",
      "short_code",
      "base_unit.name",
      "conversion_factor",
      "status",
    ],
    addBtnTitle: "addUnitOfMeasure",
    dialogTitle: {
      edit: "editUnitOfMeasure",
      create: "createUnitOfMeasure",
    },
  },
  {
    id: "finished-goods-category",
    permissions: {
      view: "view-finished-goods-category",
      create: "create-finished-goods-category",
      edit: "edit-finished-goods-category",
      delete: "delete-finished-goods-category",
    },
    searchKey: "search",
    endpoints: {
      list: "/admin/finished-goods-categories",
      createData: "/admin/finished-goods-categories/create",
      editData: (id: number) => ({
        endpoint: `/admin/finished-goods-categories/${id}/edit`,
        itemKey: "productCategory",
        optionsKey: "productCategories",
      }),
      create: "/admin/finished-goods-categories",
      update: "/admin/finished-goods-categories",
      delete: "/admin/finished-goods-categories",
    },
    formFields: [
      {
        key: "name",
        name: "name",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "description",
        name: "description",
        type: "textarea",
        value: "",
        required: true,
      },
      {
        key: "parent_id",
        name: "category_parent",
        type: "select",
        value: "",
        required: false,
        optionsKey: "categories",
        sourcePath: "parent.id",
      },
      {
        key: "status",
        name: "status",
        type: "status",
        value: "active",
        options: [],
        optionsKey: "status",
        required: true,
      },
    ],
    tableKeys: ["name", "description", "parent", "type", "status"],
    addBtnTitle: "addCategory",
    dialogTitle: {
      edit: "editCategory",
      create: "createCategory",
    },
  },
  {
    id: "raw-material-category",
    permissions: {
      view: "view-raw-material-category",
      create: "create-raw-material-category",
      edit: "edit-raw-material-category",
      delete: "delete-raw-material-category",
    },
    searchKey: "search",
    endpoints: {
      list: "/admin/raw-material-categories",
      createData: "/admin/raw-material-categories/create",
      editData: (id: number) => ({
        endpoint: `/admin/raw-material-categories/${id}/edit`,
        itemKey: "productCategory",
        optionsKey: "productCategories",
      }),
      create: "/admin/raw-material-categories",
      update: "/admin/raw-material-categories",
      delete: "/admin/raw-material-categories",
    },
    formFields: [
      {
        key: "name",
        name: "name",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "description",
        name: "description",
        type: "textarea",
        value: "",
        required: true,
      },
      {
        key: "parent_id",
        name: "category_parent",
        type: "select",
        value: "",
        required: false,
        optionsKey: "categories",
        sourcePath: "parent.id",
      },
      {
        key: "status",
        name: "status",
        type: "status",
        value: "active",
        options: [],
        optionsKey: "status",
        required: true,
      },
    ],
    tableKeys: ["name", "description", "parent", "type", "status"],
    addBtnTitle: "addCategory",
    dialogTitle: {
      edit: "editCategory",
      create: "createCategory",
    },
  },
  {
    id: "product-categories",
    permissions: {
      view: "view-product-category",
      create: "create-product-category",
      edit: "edit-product-category",
      delete: "delete-product-category",
    },
    searchKey: "search",
    endpoints: {
      list: "/admin/product-categories",
      createData: "/admin/product-categories/create",
      editData: (id: number) => ({
        endpoint: `/admin/product-categories/${id}/edit`,
        itemKey: "productCategory",
        optionsKey: "productCategories",
      }),
      create: "/admin/product-categories",
      update: "/admin/product-categories",
      delete: "/admin/product-categories",
    },
    formFields: [
      {
        key: "name",
        name: "name",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "description",
        name: "description",
        type: "textarea",
        value: "",
        required: true,
      },
      {
        key: "parent_id",
        name: "category_parent",
        type: "select",
        value: "",
        required: false,
        optionsKey: "categories",
        sourcePath: "parent.id",
      },
      {
        key: "status",
        name: "status",
        type: "status",
        value: "active",
        options: [],
        optionsKey: "status",
        required: true,
      },
    ],
    tableKeys: ["name", "description", "parent", "type", "status"],
    addBtnTitle: "addCategory",
    dialogTitle: {
      edit: "editCategory",
      create: "createCategory",
    },
  },
  {
    id: "product-attributes",
    permissions: {
      view: "view-product-attribute",
      create: "create-product-attribute",
      edit: "edit-product-attribute",
      delete: "delete-product-attribute",
    },
    searchKey: "search",
    endpoints: {
      list: "/admin/product-attributes",
      createData: "/admin/product-attributes/create",
      editData: (id: number) => ({
        endpoint: `/admin/product-attributes/${id}/edit`,
        itemKey: "ProductAttribute",
      }),
      create: "/admin/product-attributes",
      update: "/admin/product-attributes",
      delete: "/admin/product-attributes",
    },
    formFields: [
      {
        key: "name",
        name: "name",
        type: "text",
        hasTranslation: true,
        value: {
          // ar: "",
          en: "",
        },
        required: true,
      },
      {
        key: "values",
        name: "values",
        type: "values",
        value: [],
        required: true,
      },
      {
        key: "status",
        name: "status",
        type: "status",
        value: "active",
        options: [],
        optionsKey: "status",
        required: true,
      },
    ],
    tableKeys: ["name", "values", "status"],
    addBtnTitle: "addProductAttribute",
    dialogTitle: {
      edit: "editProductAttribute",
      create: "createProductAttribute",
    },
  },
];
